// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_scanner/test/coin_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;

import 'package:crypto_scanner/data/datasources/api_data_adapter.dart' as _i17;
import 'package:crypto_scanner/data/datasources/db_control.dart' as _i16;
import 'package:crypto_scanner/data/datasources/db_control_adapter.dart'
    as _i23;
import 'package:crypto_scanner/data/datasources/get_api_data.dart' as _i3;
import 'package:crypto_scanner/data/mappers/data_convertor.dart' as _i19;
import 'package:crypto_scanner/data/models/coin.dart' as _i6;
import 'package:crypto_scanner/data/models/coins.dart' as _i4;
import 'package:crypto_scanner/data/models/db_schema.dart' as _i22;
import 'package:crypto_scanner/data/models/kline.dart' as _i12;
import 'package:crypto_scanner/data/models/klines.dart' as _i10;
import 'package:crypto_scanner/data/models/map_coin.dart' as _i7;
import 'package:crypto_scanner/data/models/map_coins.dart' as _i5;
import 'package:crypto_scanner/data/models/map_kline.dart' as _i13;
import 'package:crypto_scanner/data/models/map_klines.dart' as _i11;
import 'package:crypto_scanner/data/models/tables.dart' as _i24;
import 'package:crypto_scanner/domain/entities/coin_entity.dart' as _i9;
import 'package:crypto_scanner/domain/entities/coins_entity.dart' as _i8;
import 'package:crypto_scanner/domain/entities/field.dart' as _i21;
import 'package:crypto_scanner/domain/entities/kline_entity.dart' as _i15;
import 'package:crypto_scanner/domain/entities/klines_entity.dart' as _i14;
import 'package:crypto_scanner/domain/entities/work_space.dart' as _i20;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetApiData_1 extends _i1.SmartFake implements _i3.GetApiData {
  _FakeGetApiData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoins_2 extends _i1.SmartFake implements _i4.Coins {
  _FakeCoins_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapCoins_3 extends _i1.SmartFake implements _i5.MapCoins {
  _FakeMapCoins_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoin_4 extends _i1.SmartFake implements _i6.Coin {
  _FakeCoin_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapCoin_5 extends _i1.SmartFake implements _i7.MapCoin {
  _FakeMapCoin_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoinsEntity_6 extends _i1.SmartFake implements _i8.CoinsEntity {
  _FakeCoinsEntity_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoinEntity_7 extends _i1.SmartFake implements _i9.CoinEntity {
  _FakeCoinEntity_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKlines_8 extends _i1.SmartFake implements _i10.Klines {
  _FakeKlines_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapKlines_9 extends _i1.SmartFake implements _i11.MapKlines {
  _FakeMapKlines_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKline_10 extends _i1.SmartFake implements _i12.Kline {
  _FakeKline_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapKline_11 extends _i1.SmartFake implements _i13.MapKline {
  _FakeMapKline_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKlinesEntity_12 extends _i1.SmartFake implements _i14.KlinesEntity {
  _FakeKlinesEntity_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKlineEntity_13 extends _i1.SmartFake implements _i15.KlineEntity {
  _FakeKlineEntity_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDbControl_14 extends _i1.SmartFake implements _i16.DbControl {
  _FakeDbControl_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiDataAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiDataAdapter extends _i1.Mock implements _i17.ApiDataAdapter {
  MockApiDataAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i3.GetApiData get getApiData => (super.noSuchMethod(
        Invocation.getter(#getApiData),
        returnValue: _FakeGetApiData_1(
          this,
          Invocation.getter(#getApiData),
        ),
      ) as _i3.GetApiData);

  @override
  set logger(_i2.Logger? value) => super.noSuchMethod(
        Invocation.setter(
          #logger,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set getApiData(_i3.GetApiData? value) => super.noSuchMethod(
        Invocation.setter(
          #getApiData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<_i4.Coins?> getAllCoins() => (super.noSuchMethod(
        Invocation.method(
          #getAllCoins,
          [],
        ),
        returnValue: _i18.Future<_i4.Coins?>.value(),
      ) as _i18.Future<_i4.Coins?>);

  @override
  _i18.Future<_i10.Klines?> getCoinKlines({
    String? symbol,
    int? interval,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoinKlines,
          [],
          {
            #symbol: symbol,
            #interval: interval,
            #limit: limit,
          },
        ),
        returnValue: _i18.Future<_i10.Klines?>.value(),
      ) as _i18.Future<_i10.Klines?>);
}

/// A class which mocks [DataConvertor].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataConvertor extends _i1.Mock implements _i19.DataConvertor {
  MockDataConvertor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Coins fromMapCoinsToCoins(_i5.MapCoins? mapCoins) => (super.noSuchMethod(
        Invocation.method(
          #fromMapCoinsToCoins,
          [mapCoins],
        ),
        returnValue: _FakeCoins_2(
          this,
          Invocation.method(
            #fromMapCoinsToCoins,
            [mapCoins],
          ),
        ),
      ) as _i4.Coins);

  @override
  _i5.MapCoins fromCoinsToMapCoins(_i4.Coins? coins) => (super.noSuchMethod(
        Invocation.method(
          #fromCoinsToMapCoins,
          [coins],
        ),
        returnValue: _FakeMapCoins_3(
          this,
          Invocation.method(
            #fromCoinsToMapCoins,
            [coins],
          ),
        ),
      ) as _i5.MapCoins);

  @override
  _i6.Coin fromMapCoinToCoin(_i7.MapCoin? mapCoin) => (super.noSuchMethod(
        Invocation.method(
          #fromMapCoinToCoin,
          [mapCoin],
        ),
        returnValue: _FakeCoin_4(
          this,
          Invocation.method(
            #fromMapCoinToCoin,
            [mapCoin],
          ),
        ),
      ) as _i6.Coin);

  @override
  _i7.MapCoin fromCoinToMapCoin(_i6.Coin? coin) => (super.noSuchMethod(
        Invocation.method(
          #fromCoinToMapCoin,
          [coin],
        ),
        returnValue: _FakeMapCoin_5(
          this,
          Invocation.method(
            #fromCoinToMapCoin,
            [coin],
          ),
        ),
      ) as _i7.MapCoin);

  @override
  _i8.CoinsEntity fromCoinsToCoinsEntity(_i4.Coins? coins) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromCoinsToCoinsEntity,
          [coins],
        ),
        returnValue: _FakeCoinsEntity_6(
          this,
          Invocation.method(
            #fromCoinsToCoinsEntity,
            [coins],
          ),
        ),
      ) as _i8.CoinsEntity);

  @override
  _i4.Coins fromCoinsEntityToCoins(_i8.CoinsEntity? coinsEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromCoinsEntityToCoins,
          [coinsEntity],
        ),
        returnValue: _FakeCoins_2(
          this,
          Invocation.method(
            #fromCoinsEntityToCoins,
            [coinsEntity],
          ),
        ),
      ) as _i4.Coins);

  @override
  _i9.CoinEntity fromCoinToCoinEntity(_i6.Coin? coin) => (super.noSuchMethod(
        Invocation.method(
          #fromCoinToCoinEntity,
          [coin],
        ),
        returnValue: _FakeCoinEntity_7(
          this,
          Invocation.method(
            #fromCoinToCoinEntity,
            [coin],
          ),
        ),
      ) as _i9.CoinEntity);

  @override
  _i6.Coin fromCoinEntityToCoin(_i9.CoinEntity? coinEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromCoinEntityToCoin,
          [coinEntity],
        ),
        returnValue: _FakeCoin_4(
          this,
          Invocation.method(
            #fromCoinEntityToCoin,
            [coinEntity],
          ),
        ),
      ) as _i6.Coin);

  @override
  _i8.CoinsEntity fromMapCoinsToCoinsEntity(_i5.MapCoins? mapCoins) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapCoinsToCoinsEntity,
          [mapCoins],
        ),
        returnValue: _FakeCoinsEntity_6(
          this,
          Invocation.method(
            #fromMapCoinsToCoinsEntity,
            [mapCoins],
          ),
        ),
      ) as _i8.CoinsEntity);

  @override
  _i5.MapCoins fromCoinsEntityToMapCoins(_i8.CoinsEntity? coinsEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromCoinsEntityToMapCoins,
          [coinsEntity],
        ),
        returnValue: _FakeMapCoins_3(
          this,
          Invocation.method(
            #fromCoinsEntityToMapCoins,
            [coinsEntity],
          ),
        ),
      ) as _i5.MapCoins);

  @override
  _i9.CoinEntity fromMapCoinToCoinEntity(_i7.MapCoin? mapCoin) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapCoinToCoinEntity,
          [mapCoin],
        ),
        returnValue: _FakeCoinEntity_7(
          this,
          Invocation.method(
            #fromMapCoinToCoinEntity,
            [mapCoin],
          ),
        ),
      ) as _i9.CoinEntity);

  @override
  _i7.MapCoin fromCoinEntityToMapCoin(_i9.CoinEntity? coinEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromCoinEntityToMapCoin,
          [coinEntity],
        ),
        returnValue: _FakeMapCoin_5(
          this,
          Invocation.method(
            #fromCoinEntityToMapCoin,
            [coinEntity],
          ),
        ),
      ) as _i7.MapCoin);

  @override
  _i10.Klines fromMapKlinesToKlines(_i11.MapKlines? mapKlines) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapKlinesToKlines,
          [mapKlines],
        ),
        returnValue: _FakeKlines_8(
          this,
          Invocation.method(
            #fromMapKlinesToKlines,
            [mapKlines],
          ),
        ),
      ) as _i10.Klines);

  @override
  _i11.MapKlines fromKlinesToMapKlines(_i10.Klines? klines) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlinesToMapKlines,
          [klines],
        ),
        returnValue: _FakeMapKlines_9(
          this,
          Invocation.method(
            #fromKlinesToMapKlines,
            [klines],
          ),
        ),
      ) as _i11.MapKlines);

  @override
  _i12.Kline fromMapKlineToKline(_i13.MapKline? mapKline) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapKlineToKline,
          [mapKline],
        ),
        returnValue: _FakeKline_10(
          this,
          Invocation.method(
            #fromMapKlineToKline,
            [mapKline],
          ),
        ),
      ) as _i12.Kline);

  @override
  _i13.MapKline fromKlineToMapKline(_i12.Kline? kline) => (super.noSuchMethod(
        Invocation.method(
          #fromKlineToMapKline,
          [kline],
        ),
        returnValue: _FakeMapKline_11(
          this,
          Invocation.method(
            #fromKlineToMapKline,
            [kline],
          ),
        ),
      ) as _i13.MapKline);

  @override
  _i14.KlinesEntity fromKlinesToKlinesEntity(_i10.Klines? kLines) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlinesToKlinesEntity,
          [kLines],
        ),
        returnValue: _FakeKlinesEntity_12(
          this,
          Invocation.method(
            #fromKlinesToKlinesEntity,
            [kLines],
          ),
        ),
      ) as _i14.KlinesEntity);

  @override
  _i10.Klines fromKlinesEntityToKlines(_i14.KlinesEntity? klinesEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlinesEntityToKlines,
          [klinesEntity],
        ),
        returnValue: _FakeKlines_8(
          this,
          Invocation.method(
            #fromKlinesEntityToKlines,
            [klinesEntity],
          ),
        ),
      ) as _i10.Klines);

  @override
  _i15.KlineEntity fromKlineToKlineEntity(_i12.Kline? kline) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlineToKlineEntity,
          [kline],
        ),
        returnValue: _FakeKlineEntity_13(
          this,
          Invocation.method(
            #fromKlineToKlineEntity,
            [kline],
          ),
        ),
      ) as _i15.KlineEntity);

  @override
  _i12.Kline fromKlineEntityToKline(_i15.KlineEntity? klineEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlineEntityToKline,
          [klineEntity],
        ),
        returnValue: _FakeKline_10(
          this,
          Invocation.method(
            #fromKlineEntityToKline,
            [klineEntity],
          ),
        ),
      ) as _i12.Kline);

  @override
  _i14.KlinesEntity fromMapKlinesToKlinesEntity(_i11.MapKlines? mapKlines) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapKlinesToKlinesEntity,
          [mapKlines],
        ),
        returnValue: _FakeKlinesEntity_12(
          this,
          Invocation.method(
            #fromMapKlinesToKlinesEntity,
            [mapKlines],
          ),
        ),
      ) as _i14.KlinesEntity);

  @override
  _i11.MapKlines fromKlinesEntityToMapKlines(_i14.KlinesEntity? klinesEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlinesEntityToMapKlines,
          [klinesEntity],
        ),
        returnValue: _FakeMapKlines_9(
          this,
          Invocation.method(
            #fromKlinesEntityToMapKlines,
            [klinesEntity],
          ),
        ),
      ) as _i11.MapKlines);

  @override
  _i15.KlineEntity fromMapKlineToKlineEntity(_i13.MapKline? mapKline) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromMapKlineToKlineEntity,
          [mapKline],
        ),
        returnValue: _FakeKlineEntity_13(
          this,
          Invocation.method(
            #fromMapKlineToKlineEntity,
            [mapKline],
          ),
        ),
      ) as _i15.KlineEntity);

  @override
  _i13.MapKline fromKlineEntityToMapKline(_i15.KlineEntity? klineEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromKlineEntityToMapKline,
          [klineEntity],
        ),
        returnValue: _FakeMapKline_11(
          this,
          Invocation.method(
            #fromKlineEntityToMapKline,
            [klineEntity],
          ),
        ),
      ) as _i13.MapKline);

  @override
  _i20.WorkSpace? fromTableNameToWorkSpace({required String? tableName}) =>
      (super.noSuchMethod(Invocation.method(
        #fromTableNameToWorkSpace,
        [],
        {#tableName: tableName},
      )) as _i20.WorkSpace?);

  @override
  String? fromWorkSpaceToTableName({required _i20.WorkSpace? workSpace}) =>
      (super.noSuchMethod(Invocation.method(
        #fromWorkSpaceToTableName,
        [],
        {#workSpace: workSpace},
      )) as String?);

  @override
  _i21.Field? fromColumnNameToField({required String? columnName}) =>
      (super.noSuchMethod(Invocation.method(
        #fromColumnNameToField,
        [],
        {#columnName: columnName},
      )) as _i21.Field?);

  @override
  String? fromFieldToColumnName({required _i21.Field? field}) =>
      (super.noSuchMethod(Invocation.method(
        #fromFieldToColumnName,
        [],
        {#field: field},
      )) as String?);

  @override
  String? kLineIntervalToString(int? kLineInterval) =>
      (super.noSuchMethod(Invocation.method(
        #kLineIntervalToString,
        [kLineInterval],
      )) as String?);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i2.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> get init => (super.noSuchMethod(
        Invocation.getter(#init),
        returnValue: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #t,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #d,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #i,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #w,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #wtf,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #f,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
          ],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i18.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);
}

/// A class which mocks [DbSchema].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbSchema extends _i1.Mock implements _i22.DbSchema {
  MockDbSchema() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  String? getTableName(String? tableName) =>
      (super.noSuchMethod(Invocation.method(
        #getTableName,
        [tableName],
      )) as String?);

  @override
  String? getColumnName(String? columnName) =>
      (super.noSuchMethod(Invocation.method(
        #getColumnName,
        [columnName],
      )) as String?);
}

/// A class which mocks [DbControlAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbControlAdapter extends _i1.Mock implements _i23.DbControlAdapter {
  MockDbControlAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i16.DbControl get dbControl => (super.noSuchMethod(
        Invocation.getter(#dbControl),
        returnValue: _FakeDbControl_14(
          this,
          Invocation.getter(#dbControl),
        ),
      ) as _i16.DbControl);

  @override
  set logger(_i2.Logger? value) => super.noSuchMethod(
        Invocation.setter(
          #logger,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dbControl(_i16.DbControl? value) => super.noSuchMethod(
        Invocation.setter(
          #dbControl,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<bool> initTables({required _i24.Tables? tables}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initTables,
          [],
          {#tables: tables},
        ),
        returnValue: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<bool?> isTableEmpty({required String? tableName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isTableEmpty,
          [],
          {#tableName: tableName},
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> clearTableData({required String? tableName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTableData,
          [],
          {#tableName: tableName},
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> addDbData({
    required String? tableName,
    required _i7.MapCoin? mapCoin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDbData,
          [],
          {
            #tableName: tableName,
            #mapCoin: mapCoin,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> addMultipleDbData({
    required String? tableName,
    required _i5.MapCoins? mapCoins,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMultipleDbData,
          [],
          {
            #tableName: tableName,
            #mapCoins: mapCoins,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<_i5.MapCoins?> getDbData({
    required String? tableName,
    required String? where,
    required List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDbData,
          [],
          {
            #tableName: tableName,
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i18.Future<_i5.MapCoins?>.value(),
      ) as _i18.Future<_i5.MapCoins?>);

  @override
  _i18.Future<_i5.MapCoins?> getDbMultipleData({required String? tableName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDbMultipleData,
          [],
          {#tableName: tableName},
        ),
        returnValue: _i18.Future<_i5.MapCoins?>.value(),
      ) as _i18.Future<_i5.MapCoins?>);

  @override
  _i18.Future<bool?> findDbData({
    required String? tableName,
    required String? where,
    required List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDbData,
          [],
          {
            #tableName: tableName,
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> updateDbData({
    required String? tableName,
    required Map<String, dynamic>? tableData,
    required String? where,
    required List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDbData,
          [],
          {
            #tableName: tableName,
            #tableData: tableData,
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> updateMultipleDbData({
    required String? tableName,
    required List<Map<String, dynamic>>? tableData,
    required String? updateWhereFieldIs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMultipleDbData,
          [],
          {
            #tableName: tableName,
            #tableData: tableData,
            #updateWhereFieldIs: updateWhereFieldIs,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);

  @override
  _i18.Future<bool?> deleteDbData({
    required String? tableName,
    required String? where,
    required List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDbData,
          [],
          {
            #tableName: tableName,
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i18.Future<bool?>.value(),
      ) as _i18.Future<bool?>);
}
