// Mocks generated by Mockito 5.4.6 from annotations
// in crypto_scanner/test/db_control_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:crypto_scanner/data/datasources/db_control.dart' as _i3;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:sqflite_common_ffi/sqflite_ffi.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DbControl].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbControl extends _i1.Mock implements _i3.DbControl {
  MockDbControl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  String get dbName => (super.noSuchMethod(
        Invocation.getter(#dbName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#dbName),
        ),
      ) as String);

  @override
  set db(_i5.Database? value) => super.noSuchMethod(
        Invocation.setter(
          #db,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logger(_i2.Logger? value) => super.noSuchMethod(
        Invocation.setter(
          #logger,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set dbName(String? value) => super.noSuchMethod(
        Invocation.setter(
          #dbName,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> initDb({dynamic isTest = false}) => (super.noSuchMethod(
        Invocation.method(
          #initDb,
          [],
          {#isTest: isTest},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool?> closeDb() => (super.noSuchMethod(
        Invocation.method(
          #closeDb,
          [],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool> optimizeDb() => (super.noSuchMethod(
        Invocation.method(
          #optimizeDb,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool?> isTableEmpty(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #isTableEmpty,
          [tableName],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> createTable(
    String? tableName,
    List<String>? columnNames,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTable,
          [
            tableName,
            columnNames,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> deleteTable(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #deleteTable,
          [tableName],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> renameTable(
    String? oldTableName,
    String? newTableName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameTable,
          [
            oldTableName,
            newTableName,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> findTable(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #findTable,
          [tableName],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<List<String>?> getTableNames() => (super.noSuchMethod(
        Invocation.method(
          #getTableNames,
          [],
        ),
        returnValue: _i6.Future<List<String>?>.value(),
      ) as _i6.Future<List<String>?>);

  @override
  _i6.Future<bool?> createColumn(
    String? tableName,
    String? columnName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createColumn,
          [
            tableName,
            columnName,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> deleteColumn(
    String? tableName,
    String? columnName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteColumn,
          [
            tableName,
            columnName,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> renameColumn(
    String? tableName,
    String? oldColumnName,
    String? newColumnName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameColumn,
          [
            tableName,
            oldColumnName,
            newColumnName,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> findColumn(
    String? tableName,
    String? columnName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findColumn,
          [
            tableName,
            columnName,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<List<String>?> getColumnNames(String? tableName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getColumnNames,
          [tableName],
        ),
        returnValue: _i6.Future<List<String>?>.value(),
      ) as _i6.Future<List<String>?>);

  @override
  _i6.Future<bool?> addTableData(
    String? tableName,
    Map<String, dynamic>? tableData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTableData,
          [
            tableName,
            tableData,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> deleteTableData(
    String? tableName,
    String? where,
    List<dynamic>? whereArgs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTableData,
          [
            tableName,
            where,
            whereArgs,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> updateTableData(
    String? tableName,
    Map<String, dynamic>? tableData,
    String? where,
    List<dynamic>? whereArgs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTableData,
          [
            tableName,
            tableData,
            where,
            whereArgs,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> updateMultipleTableData(
    String? tableName,
    List<Map<String, dynamic>>? tableDataList,
    String? updateWhereFieldIs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMultipleTableData,
          [
            tableName,
            tableDataList,
            updateWhereFieldIs,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<List<Map<String, dynamic>>?> getTableData(String? tableName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTableData,
          [tableName],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>?>.value(),
      ) as _i6.Future<List<Map<String, dynamic>>?>);

  @override
  _i6.Future<List<Map<String, dynamic>>?> getTableDataByParam(
    String? tableName,
    String? where,
    List<dynamic>? whereArgs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTableDataByParam,
          [
            tableName,
            where,
            whereArgs,
          ],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>?>.value(),
      ) as _i6.Future<List<Map<String, dynamic>>?>);

  @override
  _i6.Future<bool?> findTableData(
    String? tableName,
    String? where,
    List<dynamic>? whereArgs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTableData,
          [
            tableName,
            where,
            whereArgs,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> addMultipleTableData(
    String? tableName,
    List<Map<String, dynamic>>? tableDataList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMultipleTableData,
          [
            tableName,
            tableDataList,
          ],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool?> clearTableData(String? tableName) => (super.noSuchMethod(
        Invocation.method(
          #clearTableData,
          [tableName],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i2.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> get init => (super.noSuchMethod(
        Invocation.getter(#init),
        returnValue: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #t,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #d,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #i,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #w,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #wtf,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #f,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i2.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
          ],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
